version: '2'

services:
  web:
    build:
      image: web
      dockerfile: Dockerfile
    links:
      - db
    encrypted_env_file: dev.env.encrypted

  db:
    image: mysql

  gcr-dockercfg:
    image: codeship/gcr-dockercfg-generator
    add_docker: true
    encrypted_env_file: google-credentials.encrypted

  gke-deploy:
    build:
      image: deploy
      dockerfile: Dockerfile.deploy
    encrypted_env_file: google-credentials.encrypted
    add_docker: true
    volumes:
      - ./deploy:/deploy
