  version: "3.0"
  services:
    web:
      volumes:
        - .:/app
    repl:
      build: .
      command: lein repl :headless :host 0.0.0.0 :port 59789
      ports:
        - "59789:59789"
      volumes:
        - .:/app
    db:
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD="1"
