  version: "3.0"
  services:
    web:
      volumes:
        - .:/app
      env_file: dev.env
    repl:
      build: .
      command: lein repl :headless :host 0.0.0.0 :port 59789
      ports:
        - "59789:59789"
      volumes:
        - .:/app
      env_file: dev.env
    db:
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD="1"
#    pubsub:
#      image: samnco/pubsub-emulator:2016.01.22
#      ports:
#        - "8042:8042"
#      volumes:
#        - ./logs:/var/log
