{{- if .Values.curator.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "fullname" . }}
    component: curator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-curator
{{- end }}
