{{- if .Values.curator.enable }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    component: curator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}-curator-keys
  namespace: {{ .Release.Namespace }}
type: tls
data:
{{- end }}
