{{ if .Values.searchguard.enable }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    component: sginit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}-sg-admin-credentials
  namespace: {{ .Release.Namespace }}
type: tls
data:
{{- end }}
