{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: {{ template "fullname" . }}
    component: sginit
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-sginit
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - "{{ template "fullname" . }}-sg-admin-credentials"
    verbs:
      - update
      - get
{{- end -}}
