apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  DB_UPDATES_TOPIC: updates-{{ .Release.Namespace }}
  GOOGLE_CLOUD_PROJECT_ID: {{ .Values.config.GOOGLE_CLOUD_PROJECT_ID }}
  OVATION_IO_HOST_URI: {{ .Values.config.OVATION_IO_HOST_URI }}
